'''
CS 210 Project 1
Author: Arnav De
Credits: lab
Create a duck with turtle graphics, complete artistic freedom.
'''

import turtle

duck = turtle.Turtle()

def draw_outline():
    duck.penup()
    duck.goto(-100, 300)
    duck.color('black')
    duck.pendown()
    # head
    duck.right(90)
    duck.forward(100)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)

    # body
    duck.left(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(150)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(150)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)

def draw_base_layer():
    duck.penup()
    duck.goto(-100, 300)
    duck.pendown()
    duck.color('yellow')
    duck.begin_fill()
    # head
    duck.forward(100)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)

    # body
    duck.left(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(150)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(150)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(50)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.end_fill()

def draw_details():
    #eye
    duck.penup()
    duck.goto(-100, 250)
    duck.pendown()
    duck.color('black')
    duck.begin_fill()
    for i in range(4):
        duck.right(90)
        duck.forward(50)
        i += 1
    duck.end_fill()
    duck.penup()
    duck.goto(-100, 225)
    duck.color('white')
    duck.begin_fill()
    duck.pendown()
    for i in range(4):
        duck.right(90)
        duck.forward(25)
        i += 1
    duck.end_fill()

    # beak
    duck.penup()
    duck.color('orange')
    duck.goto(-200, 200)
    duck.begin_fill()
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(75)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.end_fill()

    # wing
    duck.penup()
    duck.goto(-75, 50)
    duck.pendown()
    duck.begin_fill()
    duck.right(90)
    duck.forward(100)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(100)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.right(90)
    duck.forward(100)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(50)
    duck.right(90)
    duck.forward(100)
    duck.right(90)
    duck.forward(25)
    duck.left(90)
    duck.forward(25)
    duck.end_fill()




duck.speed(10) 

draw_base_layer()
draw_details()
draw_outline()

turtle.done()